export const data = [
  {
    Gender: 'Female',
    Building: 'Moore Hall',
    Floor: '2',
    BathroomNumber: 1,
    Rating: '5',
    AverageRatingOfBuilding: '4',
  },
  {
    Gender: 'Female',
    Building: 'Paradise Palms',
    Floor: '1',
    BathroomNumber: '1',
    Rating: '2.4',
    AverageRatingOfBuilding: '3',
  },
  {
    Gender: 'Male',
    Building: 'Paradise Palms',
    Floor: '1',
    BathroomNumber: '1',
    Rating: '3.6',
    AverageRatingOfBuilding: '3',
  },
  {
    Gender: 'Male',
    Building: 'Library',
    Floor: '1',
    BathroomNumber: '1',
    Rating: '1.8',
    AverageRatingOfBuilding: '2',
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: '3',
    BathroomNumber: '2',
    Rating: '3.2',
    AverageRatingOfBuilding: '4',
  },
];

export const personalData = [
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 3.5,
    Comment: 'Not bad',
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 1,
    BathroomNumber: 2,
    Rating: 4.5,
    Comment: 'One of the best',
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 2,
    BathroomNumber: 3,
    Rating: 2.1,
    Comment: 'Pretty bad',
  },
  {
    Gender: 'Male',
    Building: 'Campus Center',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 4,
    Comment: 'Better than expected',
  },
  {
    Gender: 'Male',
    Building: 'Campus Center',
    Floor: 2,
    BathroomNumber: 1,
    Rating: 5,
    Comment: 'The best',
  },
];

export const Buildings = [
  'Administration Services Building 1',
  'Administration Services Building 2',
  'Agricultural Engineering Institute',
  'Agricultural Science',
  'Air Force ROTC Building',
  'Andrews Outdoor Theatre',
  'Architecture School',
  'Army ROTC Building',
  'Art Building',
  'Bachman Annex 2',
  'Bachman Annex 9–13',
  'Bachman Hall',
  'Bilger Addition',
  'Bilger Annex',
  'Bilger Hall',
  'Biomedical Sciences',
  'Building 37',
  'Burns Hall',
  'Campus Center',
  'Campus Services',
  'Castle Annex',
  'Castle Memorial',
  'Center for Korean Studies',
  'C-MORE Hale (Center for Microbial Oceanography: Research and Education)',
  'Cooke Field',
  'Crawford Hall',
  'Dance Building',
  'Dean Hall',
  'Diving Safety Program',
  'Dole Street Offices',
  'Dole Street Parking Structure',
  'Edmondson Hall',
  'Energy House',
  'Engineering Quad',
  'Environmental Health and Safety Offices',
  'Environmental Protection Facility',
  'Everly Hall',
  'Federal Credit Union',
  'Financial Management Office',
  'Food Science and Technology',
  'Frear Hall',
  'Gartley Hall',
  'Gateway House',
  'George Hall',
  'Gilmore Hall',
  'Gym 1',
  'Gym 2',
  'Hale Aloha Lehua',
  'Hale Aloha ʻIlima',
  'Hale Aloha Mokihana',
  'Hale Aloha Lokelani',
  'Hale Aloha Cafeteria',
  'Hale Ānuenue',
  'Hale Halawai',
  'Hale Kahawai',
  'Hale Kuahine',
  'Hale Laulima',
  'Hale Mānoa',
  'Hale Noelani',
  'Hale Wainani',
  'Hamilton Library',
  'Hawaiʻi English Language Program',
  'Hawaiʻi Hall',
  'Hawaiʻi Institute of Geophysics',
  'Health Services',
  'Hemenway Hall',
  'Henke Hall',
  'Holmes Hall',
  'Horticulture Greenhouses',
  'Horticulture Headhouse',
  'Information Technology Center',
  'Institute for Astronomy',
  'Jefferson Hall',
  'John A. Burns School of Medicine',
  'Johnson Hall A',
  'Johnson Hall B',
  'Kahanamoku Pool',
  'Kamakakūokalani Center for Hawaiian Studies',
  'Kauʻiokahaloa Iki Faculty Housing',
  'Kauʻiokahaloa Nui Faculty Housing',
  'Keller Hall',
  'Kennedy Theatre',
  'KHET TV',
  'Klum Gym',
  'Krauss Annex 19',
  'Krauss Annex U',
  'Krauss Hall',
  'Kuykendall Annex',
  'Kuykendall Hall',
  'Lab School Portables 1–4',
  'Landscaping',
  'Law Library',
  'Law School',
  'Lincoln Hall',
  'Lincoln Hall Annex',
  'Magoon Facility',
  'Maile Way Annex',
  'Marine Sciences Building',
  'Miller Hall',
  'Miller Hall Annex',
  'Moore Hall',
  'Multipurpose Building',
  'Murakami Stadium',
  'Music Building Complex',
  'National Marine Fisheries Service',
  'Newman Center',
  'NREM Greenhouse',
  'Office of Procurement and Real Property Management',
  'Orvis Auditorium',
  'Pacific Biosciences Research Center',
  'Pacific Ocean Science and Technology',
  'Paradise Palms Cafe',
  'Parking Structure',
  'Physical Education Athletic Complex',
  'Physical Plant Building',
  'Physical Science Building',
  'Pope Laboratory',
  'Practice Fields',
  'Public Safety',
  'Queen Liliʻuokalani Center for Student Services',
  'Sakamaki Hall',
  'Saunders Hall',
  'Sherman Laboratory',
  'Shidler College of Business',
  'Shops',
  'Sinclair Annex',
  'Sinclair',
  'Snyder Hall',
  'Softball Stadium',
  'Spalding Hall',
  'Speech Pathology/Audiology',
  'St. John Plant Science Lab',
  'Stan Sheriff Center',
  'Tennis Courts',
  'Thrift Shop',
  'Transportation Services',
  'University High School 1',
  'University High School 2',
  'University High School 3',
  'University of Hawaiʻi Press',
  'USDA Fruit Fly Lab',
  'Waʻahila Faculty Housing',
  'Warehouse',
  'Warrior Recreation Center',
  'Watanabe Hall',
  'Webster Hall',
  'Wist Annex 1',
  'Wist Hall',
];

export const Floors = [
  '1',
  '2',
  '3',
  '4',
  '5',
];

export const Genders = [
  'Male',
  'Female',
];
