export const data = [
  {
    Gender: 'Female',
    Building: 'Moore Hall',
    Floor: 2,
    BathroomNumber: 1,
    Rating: 5,
    AverageRatingOfBuilding: 4,
  },
  {
    Gender: 'Female',
    Building: 'Paradise Palms',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 2.4,
    AverageRatingOfBuilding: 3,
  },
  {
    Gender: 'Male',
    Building: 'Paradise Palms',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 3.6,
    AverageRatingOfBuilding: 3,
  },
  {
    Gender: 'Male',
    Building: 'Library',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 1.8,
    AverageRatingOfBuilding: 2,
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 3,
    BathroomNumber: 2,
    Rating: 3.2,
    AverageRatingOfBuilding: 4,
  },
];

export const personalData = [
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 3.5,
    Comment: 'Not bad',
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 1,
    BathroomNumber: 2,
    Rating: 4.5,
    Comment: 'One of the best',
  },
  {
    Gender: 'Male',
    Building: 'Moore Hall',
    Floor: 2,
    BathroomNumber: 3,
    Rating: 2.1,
    Comment: 'Pretty bad',
  },
  {
    Gender: 'Male',
    Building: 'Campus Center',
    Floor: 1,
    BathroomNumber: 1,
    Rating: 4,
    Comment: 'Better than expected',
  },
  {
    Gender: 'Male',
    Building: 'Campus Center',
    Floor: 2,
    BathroomNumber: 1,
    Rating: 5,
    Comment: 'The best',
  },
];
